import {
	GraphQLFloat,
	GraphQLID,
	GraphQLInt,
	GraphQLList,
	GraphQLNonNull,
	GraphQLString,
} from "graphql";
import { equipmentResolvers } from "../resolvers/equipmentResolvers.js";

import EquipmentType from "./types/EquipmentType.js";

const EquipmentQuery = {
	equipment: {
		type: EquipmentType,
		args: { id: { type: GraphQLID } },
		resolve: equipmentResolvers.getEquipmentById,
	},
	equipments: {
		type: GraphQLList(EquipmentType),
		resolve: equipmentResolvers.getAllEquipments,
	},
	searchEquipments: {
		type: GraphQLList(EquipmentType),
		args: {
			name: { type: GraphQLString },
			type: { type: GraphQLString },
			brand: { type: GraphQLString },
			priceFrom: { type: GraphQLFloat },
			priceTo: { type: GraphQLFloat },
			flexibility: { type: GraphQLString },
			frame: { type: GraphQLString },
			shaft: { type: GraphQLString },
			weightGrip: { type: GraphQLString },
			stringTension: { type: GraphQLString },
			balance: { type: GraphQLString },
			gauge: { type: GraphQLString },
			length: { type: GraphQLString },
			coreMaterial: { type: GraphQLString },
			outerMaterial: { type: GraphQLString },
			coating: { type: GraphQLString },
			durability: { type: GraphQLInt },
			repulsionPower: { type: GraphQLInt },
			control: { type: GraphQLInt },
			hittingSound: { type: GraphQLInt },
			upperMaterial: { type: GraphQLString },
			midsoleMaterial: { type: GraphQLString },
			outsoleMaterial: { type: GraphQLString },
			technology: { type: GraphQLString },
			colors: { type: GraphQLList(GraphQLString) },
			playerStyle: { type: GraphQLString },
			playerLevel: { type: GraphQLString },
		},
		resolve: equipmentResolvers.searchEquipments,
	},
	suitableRacquets: {
		type: GraphQLList(EquipmentType),
		resolve: equipmentResolvers.findSuitableRacquets,
	},
	suitableStrings: {
		type: GraphQLList(EquipmentType),
		resolve: equipmentResolvers.findSuitableStrings,
	},
};

const EquipmentMutation = {
	addEquipment: {
		type: EquipmentType,
		args: {
			name: { type: GraphQLNonNull(GraphQLString) },
			type: { type: GraphQLNonNull(GraphQLString) },
			brand: { type: GraphQLNonNull(GraphQLString) },
			price: { type: GraphQLFloat },
			imageUrl: { type: GraphQLString },
			link: { type: GraphQLString },
			flexibility: { type: GraphQLString },
			frame: { type: GraphQLString },
			shaft: { type: GraphQLString },
			weightGrip: { type: GraphQLList(GraphQLString) },
			stringTension: { type: GraphQLList(GraphQLString) },
			balance: { type: GraphQLString },
			gauge: { type: GraphQLString },
			length: { type: GraphQLString },
			coreMaterial: { type: GraphQLString },
			outerMaterial: { type: GraphQLString },
			coating: { type: GraphQLString },
			durability: { type: GraphQLInt },
			repulsionPower: { type: GraphQLInt },
			control: { type: GraphQLInt },
			hittingSound: { type: GraphQLInt },
			upperMaterial: { type: GraphQLString },
			midsoleMaterial: { type: GraphQLString },
			outsoleMaterial: { type: GraphQLString },
			technology: { type: GraphQLString },
			colors: { type: GraphQLList(GraphQLString) },
			playerStyle: { type: GraphQLString },
			playerLevel: { type: GraphQLString },
		},
		resolve: equipmentResolvers.addEquipment,
	},
	updateEquipment: {
		type: EquipmentType,
		args: {
			id: { type: GraphQLNonNull(GraphQLID) },
			name: { type: GraphQLString },
			type: { type: GraphQLString },
			brand: { type: GraphQLString },
			price: { type: GraphQLFloat },
			picture: { type: GraphQLString },
			link: { type: GraphQLString },
			flexibility: { type: GraphQLString },
			frame: { type: GraphQLString },
			shaft: { type: GraphQLString },
			weightGrip: { type: GraphQLList(GraphQLString) },
			stringTension: { type: GraphQLList(GraphQLString) },
			balance: { type: GraphQLString },
			gauge: { type: GraphQLString },
			length: { type: GraphQLString },
			coreMaterial: { type: GraphQLString },
			outerMaterial: { type: GraphQLString },
			coating: { type: GraphQLString },
			durability: { type: GraphQLInt },
			repulsionPower: { type: GraphQLInt },
			control: { type: GraphQLInt },
			hittingSound: { type: GraphQLInt },
			upperMaterial: { type: GraphQLString },
			midsoleMaterial: { type: GraphQLString },
			outsoleMaterial: { type: GraphQLString },
			technology: { type: GraphQLString },
			colors: { type: GraphQLList(GraphQLString) },
			playerStyle: { type: GraphQLString },
			playerLevel: { type: GraphQLString },
		},
		resolve: equipmentResolvers.updateEquipment,
	},
	deleteEquipment: {
		type: EquipmentType,
		args: { id: { type: GraphQLNonNull(GraphQLID) } },
		resolve: equipmentResolvers.deleteEquipment,
	},
};

export { EquipmentMutation, EquipmentQuery };
